name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - name: Google Cloud Authentication
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: 'website-serv-acc@static-website-proj5.iam.gserviceaccount.com' # my-service-account@my-project.iam.gserviceaccount.com
          workload_identity_provider: 'projects/210183724594/locations/global/workloadIdentityPools/github/providers/my-repo'

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
